ZON-3362: Index properties of ``IVolume`` objects.
ZeitOnline/zeit.solr pull request #4
Opened 2016-09-23 09:44 UTC by wosc

2016-09-23 12:11 UTC, florianpilz commented on src/zeit/solr/tests/test_converter.py
> +            volume.uniqueId, xml.xpath('//field[@name="uniqueId"]')[0].text)
In assertions generell lieber duplizieren, also explizit `'http://xml.zeit.de/volume'` hinschreiben.

2016-09-23 12:12 UTC, florianpilz commented on src/zeit/solr/converter.py
> +        indexes = self.solr_mapping
Hatte das was mit dem PR zu tun oder generelles Cleanup?

2016-09-23 12:13 UTC, florianpilz commented on src/zeit/solr/converter.py
> +        self.solr = 'date_digital_published'
Dass `self.solr` den Knoten-Namen bestimmt ist etwas unintuitiv. 😞

2016-09-23 12:14 UTC, florianpilz commented on src/zeit/solr/converter.py
> +        if value.product:
Hm, dass würde ich genau umgekehrt sehen. `value.product` wird es laut `IVolume` immer geben bzw. wird von der formlib validiert. `value.date_gitial_published` hingegen ist nicht required ...

2016-09-23 12:19 UTC, florianpilz commented on src/zeit/solr/converter.py
> +    # XXX kludgy special case to only apply to IVolume objects and not to other
Oh my. ☁️ Man will ja eigentlich nie auf ein anderes Objekt adaptieren oder? Sondern immer nur Infos vom selben Objekt? Dann könnte man nach `value = self.get_adapter(index.interface)` im `convert` vielleicht einfach sicherstellen ob das `value` noch dasselbe Objekt ist?

2016-09-23 12:19 UTC, florianpilz commented on src/zeit/solr/tests/test_converter.py
> +        self.assertFalse(xml.xpath('//field[@name="date_digital_published"]'))
🐝

2016-09-23 12:21 UTC, florianpilz requested changes
Ich denke die Fallunterscheidung, ob es `date_digital_published` überhaupt gibt muss noch rein. Der Rest ist nicht so wichtig.

Finde die Lösung insgesamt nicht soo dolle (was ja an der Mechanik liegt), aber sollte funktionieren.

2016-09-26 07:29 UTC, wosc commented on src/zeit/solr/tests/test_converter.py
> +            volume.uniqueId, xml.xpath('//field[@name="uniqueId"]')[0].text)
Hier wird's philosophisch. Bei zu vielen Literalen wird aus meiner Sicht die Funktion/Beziehung nicht klar. Und für alles Variablen einziehen, nur damit es garantiert literal da steht, find ich teilweise Overkill.

2016-09-26 07:29 UTC, wosc commented on src/zeit/solr/converter.py
> +    # XXX kludgy special case to only apply to IVolume objects and not to other
Das nächste Mal schreib ich in die PR-Beschreibung mit rein, dass ich absichtlich entschieden habe, die Mechanik so zu lassen, auch wenn sie doof ist (und nicht das neuere schönere tollere von zeit.retresco einzuziehen), weil das zeit.solr ne Halbwertszeit von <6 Monaten hat und sich das IMHO nicht mehr lohnt.

2016-09-26 07:49 UTC, wosc commented on src/zeit/solr/converter.py
> +        indexes = self.solr_mapping
drive-by cleanup. war auch in nem separaten Commit.

2016-09-26 07:50 UTC, wosc commented on src/zeit/solr/converter.py
> +        if value.product:
Wenn wir das Erscheinungsdatum zum Sortieren/Vorgänger/Nachfolger benutzen, sollten wir das auf IVolume dann vielleicht required machen? (Was immernoch nicht heißt, dass es vorhanden ist, in Punkto die ganzen alten 1950er Jahrgänge...)

2016-09-27 11:55 UTC, merged